inherits: ..\\languages-formats.yml

dimensions:
- alias: product
  values: [net]
- alias:  operation
  values: [orientation]
- alias:  fileformat
  values: [word, excel, powerpoint, docx, xlsx, pptx, epub, xps]

generationRules:
  include:
  - fileformat[word, excel, powerpoint, docx, xlsx, pptx, epub, xps]
  
outputPath: "merger\\{product}\\{operation}\\{fileformat}.{lang}.md"

dictionaries: [ ..\\..\\data\\products.json ]
