inherits: ..\\languages-formats.yml

dimensions:
- alias: product
  values: [net]
- alias:  operation
  values: [combine]
- alias:  fileformat
  values: [docx, pdf, pptx, xlsx, epub]

generationRules:
  include:
  - fileformat[docx, pdf, pptx, xlsx, epub]
  
outputPath: "merger\\{product}\\{operation}\\{fileformat}.{lang}.md"

dictionaries: [ ..\\..\\data\\products.json ]
