inherits: products.yml

dimensions: 
- alias: ext
  values: ["excel", "image", "onenote", "visio", "web", "word", "worksheet", "doc", "docm", "docx", "dot", "dotm", "dotx", "epub", "html", "mht", "mhtml", "odp", "ods", "odt", "one", "otp", "ott", "pdf", "pps", "ppsx", "ppt", "pptx", "rtf", "tex", "vdx", "vsdm", "vsdx", "vssm", "vssx", "vstm", "vstx", "vsx", "vtx", "xlam", "xls", "xlsb", "xlsm", "xlsx", "xlt", "xltm", "xltx", "xps"]

generationRules:
  exclude:
    - ext[excel, image, onenote, visio, web, word, worksheet]
  include:
##  - ext[odt]

dictionaries: [ "..\\data\\extract_{product}.{lang}.json", "..\\data\\extract_{product}.json", "..\\data\\otherformats.json" ]

outputPath: "{product}\\extract\\{ext}.{lang}.md"