inherits: ..\\languages-formats.yml

dimensions:
- alias: product
  values: [nodejs-java]
- alias:  operation
  values: [rotate]
- alias:  fileformat
  values: [pdf, epub, xps]

generationRules:
  include:
  - fileformat[pdf, epub, xps]
  
outputPath: "merger\\{product}\\{operation}\\{fileformat}.{lang}.md"

dictionaries: [ ..\\..\\data\\products.json ]
