inherits: ..\\languages-formats.yml

dimensions:
- alias: product
  values: [net]
- alias:  operation
  values: [extract]
- alias:  fileformat
  values: [word, excel, powerpoint, visio, pdf, docx, xlsx, pptx, tiff, epub, html, mhtml, xps]

generationRules:
  include:
  - fileformat[word, excel, powerpoint, visio, pdf, docx, xlsx, pptx, tiff, epub, html, mhtml, xps]
  
outputPath: "merger\\{product}\\{operation}\\{fileformat}.{lang}.md"

dictionaries: [ ..\\..\\data\\products.json ]
