inherits: ..\\languages-formats.yml

dimensions:
- alias: product
  values: [nodejs-java]
- alias:  operation
  values: [join]
- alias:  fileformat
  values: [word, excel, powerpoint, image, visio, pdf, docx, xlsx, pptx, bmp, jpeg, jpg, png, svg, tiff, csv, epub, html, mhtml, txt, xps, zip]

generationRules:
  include:
  - fileformat[word, excel, powerpoint, image, visio, pdf, docx, xlsx, pptx, bmp, jpeg, jpg, png, svg, tiff, csv, epub, html, mhtml, txt, xps, zip]
  
outputPath: "merger\\{product}\\{operation}\\{fileformat}.{lang}.md"

dictionaries: [ ..\\..\\data\\products.json ]
